# -*- coding: utf-8 -*-
"""aula0004.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19mdq2lHsgvcRMH1cN3lKYdvn28UtlA4g
"""

import pandas as pd
import numpy as np

# Criando o dataset do slide 36
data = {
    'Idade': ['infantil', 'infantil', 'infantil', 'infantil', 'adolescente', 'adolescente', 'adolescente', 'adolescente', 'adolescente', 'adulto', 'adulto', 'adulto', 'adulto', 'adulto', 'adulto'],
    'Diagnóstico': ['miopia', 'miopia', 'hipermetropia', 'hipermetropia', 'miopia', 'miopia', 'miopia', 'hipermetropia', 'hipermetropia', 'miopia', 'miopia', 'miopia', 'hipermetropia', 'hipermetropia', 'hipermetropia'],
    'Astigmatismo': ['não', 'sim', 'não', 'sim', 'não', 'sim', 'não', 'não', 'sim', 'não', 'sim', 'sim', 'não', 'sim', 'não'],
    'Taxa_lacrimal': ['reduzida', 'normal', 'normal', 'normal', 'reduzida', 'reduzida', 'normal', 'reduzida', 'normal', 'normal', 'normal', 'normal', 'reduzida', 'normal', 'normal'],
    'Tipo_de_lente': ['nenhuma', 'gelatinosa', 'gelatinosa', 'dura', 'gelatinosa', 'nenhuma', 'dura', 'gelatinosa', 'dura', 'gelatinosa', 'dura', 'gelatinosa', 'nenhuma', 'gelatinosa', 'gelatinosa']
}

df = pd.DataFrame(data)

def calcular_probabilidades_suavizadas(df, classe_col, alpha=1):
    classes = df[classe_col].unique()
    tabelas = {}

    # Probabilidades a priori das classes P(v_j)
    priori = (df[classe_col].value_counts() + alpha) / (len(df) + len(classes) * alpha)
    tabelas['priori'] = priori

    # Probabilidades condicionais P(a_i | v_j)
    for col in df.columns:
        if col == classe_col: continue

        # Tabela de frequências
        ct = pd.crosstab(df[col], df[classe_col])
        # Aplicando Laplace
        prob_cond = (ct + alpha) / (df[classe_col].value_counts() + len(df[col].unique()) * alpha)
        tabelas[col] = prob_cond

    return tabelas

probs = calcular_probabilidades_suavizadas(df, 'Tipo_de_lente')
print("Probabilidades Suavizadas Calculadas!")

def classificar_naive_bayes(paciente, probs):
    resultados = {}
    for classe in probs['priori'].index:
        # P(v_j)
        p_total = probs['priori'][classe]

        # Multiplicando pelas condicionais P(a_i | v_j)
        for attr, valor in paciente.items():
            p_total *= probs[attr].loc[valor, classe]

        resultados[classe] = p_total

    # Normalização (Soma 100%)
    soma = sum(resultados.values())
    normalizado = {k: v / soma for k, v in resultados.items()}
    return normalizado

novo_paciente = {
    'Idade': 'infantil',
    'Diagnóstico': 'hipermetropia',
    'Astigmatismo': 'não',
    'Taxa_lacrimal': 'reduzida'
}

previsao = classificar_naive_bayes(novo_paciente, probs)
print(f"Previsão Normalizada: {previsao}")