# -*- coding: utf-8 -*-
"""Aula0006.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R70G9k2-AvcuopbXV9RmB4t3cHP_T_dC
"""

import pandas as pd

data = [
    ['young', 'myope', 'no', 'reduced', 'none'],
    ['young', 'myope', 'no', 'normal', 'soft'],
    ['young', 'myope', 'yes', 'reduced', 'none'],
    ['young', 'myope', 'yes', 'normal', 'hard'],
    ['young', 'hypermetrope', 'no', 'reduced', 'none'],
    ['young', 'hypermetrope', 'no', 'normal', 'soft'],
    ['young', 'hypermetrope', 'yes', 'reduced', 'none'],
    ['young', 'hypermetrope', 'yes', 'normal', 'hard'],

    ['pre-presbyopic', 'myope', 'no', 'reduced', 'none'],
    ['pre-presbyopic', 'myope', 'no', 'normal', 'soft'],
    ['pre-presbyopic', 'myope', 'yes', 'reduced', 'none'],
    ['pre-presbyopic', 'myope', 'yes', 'normal', 'hard'],
    ['pre-presbyopic', 'hypermetrope', 'no', 'reduced', 'none'],
    ['pre-presbyopic', 'hypermetrope', 'no', 'normal', 'soft'],
    ['pre-presbyopic', 'hypermetrope', 'yes', 'reduced', 'none'],
    ['pre-presbyopic', 'hypermetrope', 'yes', 'normal', 'none'],

    ['presbyopic', 'myope', 'no', 'reduced', 'none'],
    ['presbyopic', 'myope', 'no', 'normal', 'none'],
    ['presbyopic', 'myope', 'yes', 'reduced', 'none'],
    ['presbyopic', 'myope', 'yes', 'normal', 'hard'],
    ['presbyopic', 'hypermetrope', 'no', 'reduced', 'none'],
    ['presbyopic', 'hypermetrope', 'no', 'normal', 'soft'],
    ['presbyopic', 'hypermetrope', 'yes', 'reduced', 'none'],
    ['presbyopic', 'hypermetrope', 'yes', 'normal', 'none'],
]

columns = ['age', 'spectacle', 'astigmatism', 'tear_rate', 'lenses']
df = pd.DataFrame(data, columns=columns)

# Visualizar a distribuição das classes (conforme o PDF)
print(df['lenses'].value_counts()) # Deve mostrar 15 none, 5 soft, 4 hard

def algoritmo_prism(df_original, classe_alvo):
    conjunto_atual = df_original.copy()
    regras_da_classe = []

    # Enquanto houver exemplos da classe alvo não cobertos
    while len(conjunto_atual[conjunto_atual['lenses'] == classe_alvo]) > 0:
        subconjunto_regra = conjunto_atual.copy()
        antecedentes = []
        atributos_disponiveis = ['age', 'spectacle', 'astigmatism', 'tear_rate']

        # Construir uma regra individual
        while True:
            melhor_p = -1.0
            melhor_par = None
            melhor_cobertura = -1

            for attr in atributos_disponiveis:
                valores = subconjunto_regra[attr].unique()
                for val in valores:
                    # Filtra exemplos que possuem este par atributo-valor
                    amostra = subconjunto_regra[subconjunto_regra[attr] == val]

                    cobertura_positiva = len(amostra[amostra['lenses'] == classe_alvo])
                    total_amostra = len(amostra)

                    probabilidade = cobertura_positiva / total_amostra

                    # Critério de seleção do PRISM com desempate por cobertura
                    if (probabilidade > melhor_p) or (probabilidade == melhor_p and cobertura_positiva > melhor_cobertura):
                        melhor_p = probabilidade
                        melhor_par = (attr, val)
                        melhor_cobertura = cobertura_positiva

            if melhor_par:
                antecedentes.append(f"{melhor_par[0]} = {melhor_par[1]}")
                subconjunto_regra = subconjunto_regra[subconjunto_regra[melhor_par[0]] == melhor_par[1]]
                atributos_disponiveis.remove(melhor_par[0])

                # Se a regra atingiu 100% de precisão ou acabaram os atributos
                if melhor_p == 1.0 or not atributos_disponiveis:
                    break
            else:
                break

        # Salva a regra e remove os exemplos cobertos do conjunto principal
        regra_final = " AND ".join(antecedentes)
        regras_da_classe.append(f"IF {regra_final} THEN lenses = {classe_alvo}")

        # O conjunto original é reduzido removendo quem a regra perfeita cobriu
        indices_cobertos = subconjunto_regra.index
        conjunto_atual = conjunto_atual.drop(indices_cobertos)

    return regras_da_classe

# Ordem sugerida no seu PDF: hard, depois soft, depois none
classes = ['hard', 'soft', 'none']

for alvo in classes:
    print(f"\n--- Gerando Regras para a Classe: {alvo.upper()} ---")
    regras = algoritmo_prism(df, alvo)
    for i, r in enumerate(regras, 1):
        print(f"R{i}: {r}")

print("\nProcesso concluído com sucesso!")