# -*- coding: utf-8 -*-
"""aula0005.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xpbK6hxxXznf0MC7iUu31lQl3Yv1_XDL
"""

import pandas as pd
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.preprocessing import LabelEncoder
import matplotlib.pyplot as plt

# Dados do exercício (Lentes de Contato)
data = {
    'Idade': ['infantil', 'infantil', 'infantil', 'infantil', 'adolescente', 'adolescente', 'adolescente', 'adolescente', 'adolescente', 'adulto', 'adulto', 'adulto', 'adulto', 'adulto', 'adulto'],
    'Diagnóstico': ['miopia', 'miopia', 'hipermetropia', 'hipermetropia', 'miopia', 'miopia', 'miopia', 'hipermetropia', 'hipermetropia', 'miopia', 'miopia', 'miopia', 'hipermetropia', 'hipermetropia', 'hipermetropia'],
    'Astigmatismo': ['não', 'sim', 'não', 'sim', 'não', 'sim', 'não', 'não', 'sim', 'não', 'sim', 'sim', 'não', 'sim', 'não'],
    'Taxa_lacrimal': ['reduzida', 'normal', 'normal', 'normal', 'reduzida', 'reduzida', 'normal', 'reduzida', 'normal', 'normal', 'normal', 'normal', 'reduzida', 'normal', 'normal'],
    'Tipo_de_lente': ['nenhuma', 'gelatinosa', 'gelatinosa', 'dura', 'gelatinosa', 'nenhuma', 'dura', 'gelatinosa', 'dura', 'gelatinosa', 'dura', 'gelatinosa', 'nenhuma', 'gelatinosa', 'gelatinosa']
}

df = pd.DataFrame(data)

# Convertendo texto para números (Label Encoding)
le = LabelEncoder()
df_encoded = df.apply(le.fit_transform)

X = df_encoded.drop('Tipo_de_lente', axis=1)
y = df_encoded['Tipo_de_lente']

# Criando o classificador com Entropia (Cálculo de Ganho de Informação)
clf = DecisionTreeClassifier(criterion='entropy', random_state=42)
clf.fit(X, y)

plt.figure(figsize=(12,8))
plot_tree(clf,
          feature_names=X.columns,
          class_names=le.classes_,
          filled=True,
          rounded=True)
plt.title("Árvore de Decisão - Lentes de Contato")
plt.show()